name: 'Free Pascal Compiler'
description: 'Compile Pascal code using FPC'
author: 'suve'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  exclude-path:
    description: 'List of paths to ignore'
    required: false
    default: ''
  fail-on:
    description: 'Strictness level'
    required: false
    default: 'e'
  flags:
    description: 'FPC flags (space-separated)'
    required: false
    default: ''
  fpc:
    description: 'Full path to fpc executable'
    required: false
    default: ''
  source:
    description: 'Main source file to compile'
    required: true
  user-defined:
    description: 'Display user-defined messages'
    required: false
    default: '*'
  verbosity:
    description: 'Verbosity level'
    required: false
    default: 'ew'
  workdir:
    description: 'Working directory to use'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
